### ISSUE TITLE
Please mirror sdl12-compat as well

### ISSUE THREAD

**Issue by Croydon** [SDL-mirror/tools#1]
Hey @Yoplitein! 

Thanks for your mirrors! Could you perhaps add sdl12-compat as well?

https://hg.libsdl.org/sdl12-compat/
https://www.patreon.com/posts/project-sdl12-25321792

**Comment by Yoplitein** [comment]
No problem. Happy hacking!

**Comment by Croydon** [comment]
Thanks!
